# Generated by Django 4.1.1 on 2024-03-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_alter_spotlistuser_spotlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotMapIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconUrl', models.URLField(default='https://spotbook-media.s3.amazonaws.com/media//icons/default')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
