# Generated by Django 4.1.1 on 2024-03-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0005_spotmapicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotmapicon',
            name='name',
            field=models.CharField(default='default', max_length=32),
        ),
    ]
