# Generated by Django 4.1.1 on 2023-08-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='C:/Users/User/Documents/GitHub/spotbook/media/default_profile_picture.png', null=True, upload_to='profiles/'),
        ),
    ]
