# Generated by Django 4.1.1 on 2023-09-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clip-images/'),
        ),
    ]
